import { getSession, useSession } from 'next-auth/react';
import Head from 'next/head';
import Header from '../components/Header/Header';

export default function Home() {
  const {data:session,status}= useSession();
 

  return (
    <div className="">
      <Head>
        <title>Disney+</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header session={session}/>
  
      
    </div>
  )
}

export async function  getServerSideProps(context){
   
  const session = await getSession(context);
  return {
    props: {
      session,
    },
  }
}